import { Sync } from '../shared/interfaces/sync';
import { ProjectWarrantyTypeRequested } from './project-warranty-type-requested.model';
import { PsbNoRequired } from './psb_no_required.model';
import { PsbOption } from './psb-option.model';
import { PsbChimney } from './psb_chimney.model';
import { PsbCrickets } from './psb_crickets.model';
import { PsbSkylight } from './psb_skylight.model';
import { PsbVerified } from './psb_verified.model';
import { PsbUpgradesVent } from './psb_upgrades_vents.model';
import { PsbUpgrade } from './psb_upgrades.model';
import { PsbSlope } from './psb-slope.model';
import { PsbLayer } from './psb-layer.model';
import { PsbSelectedMaterial } from './psb_selected_material.model';
import { PsbMaterialCalculation } from './psb-material-calculation.model';
import { PsbLouveredVent } from './psb-louvrevents.model';
import { PsbSoffitVent } from './psb-soffitvents.model';

export class PsbMeasures implements Sync {
  id?: any;
  wasting: number;
  id_inwshield_rows: number;
  id_project_building: number;
  ridge_lf?: any;
  hips_lf?: any;
  eves_rakes_lf_flat_roof?: number;
  id_metal_eves_rakes_flat_roof?: any;
  eves_starters_lf_low_slope?: any;
  id_metal_eves_starters_low_slope?: any;
  rakes_lf_low_steep_slope?: any;
  rakes_lf_steep_slope?: any;
  id_metal_rakes_low_steep_slope?: any;
  valleys_lf_low_slope?: number;
  eves_starters_lf_steep_slope?: any;
  id_metal_lss_starters_lf?: any;
  valleys_lf_steep_slope?: any;
  project_warranty_type_requested: ProjectWarrantyTypeRequested[];
  id_project_warranty_option: number;
  id_cost_int_windw: number;
  verified_general?: boolean;
  verified_roof_slope?: boolean;
  psb_verifieds?: PsbVerified[];
  psb_no_requireds?: PsbNoRequired[];
  misc_roof_caulking_pc: number;
  misc_spary_paint_pc: number;
  misc_poor_access_dll: number;
  misc_miscellaneous_dll: number;
  misc_permit_dll: number;
  misc_contingency_fund_dll: number;
  
  isVent_modify: boolean;
  vent_j_vent_4_pc: number;
  vent_j_vent_4_replace: number;
  vent_j_vent_4_remove: number;
  vent_j_vent_4_add: number;
  vent_j_vent_4_relocate: number;
  vent_j_vent_6_pc: number;
  vent_j_vent_6_replace: number;
  vent_j_vent_6_remove: number;
  vent_j_vent_6_add: number;
  vent_j_vent_6_relocate: number;
  
  vent_is_ridgevent_in_place: boolean;
  vent_is_ridgevent_add: boolean;
  vent_is_ridgevent_be_replace: boolean;

  vent_ridgevent_lf: number;
  vent_metal_artict: number;
  vent_metal_artict_replace: number;
  vent_metal_artict_add: number;
  vent_metal_artict_remove: number;
  vent_metal_artict_relocate: number;
  vent_metal_artict_cut_in_pc: number;

  vent_solar_power_vent_pc: number;
  vent_solar_power_vent_pc_replace: number;
  vent_solar_power_vent_pc_add: number;
  vent_solar_power_vent_pc_remove: number;
  vent_solar_power_vent_pc_relocate: number;

  vent_power_vent_pc: number;
  vent_power_vent_pc_replace: number;
  vent_power_vent_pc_add: number;
  vent_power_vent_pc_remove: number;
  vent_power_vent_pc_relocate: number;

  isridgeVent: boolean;
  flash_step_4_4_8_lf: number;
  flash_rolled_metal_20_50_lf: number;
  flash_end_wall_metal_3_5_10_lf: number;
  flash_pipe_3_in_1_pc: number;
  flash_pipe_2_in_1_pc: number;
  flash_retrofit_pipe_pc: number;
  flash_step_4_4_12_lf: number;
  vent_soffit_eves_in: number;
  vent_soffit_rakes_in: number;
  vent_additional_soffit_eves_sf: number;
  vent_cut_sidding_walls_lf: number;
  out_additional_fuel_dll: number;
  out_estimated_days_days: number;
  out_estimated_roofers_qty: number;
  out_loding_rate_dll: number;
  out_id_loding_type: number;
  out_travel_time_hrs: number;
  isModified: boolean;
  psb_crickets: PsbCrickets[];
  psb_options: PsbOption[];
  psb_chimneys: PsbChimney[];
  psb_skylights: PsbSkylight[];
  psb_upgrades_vent: PsbUpgradesVent;
  psb_upgrades: PsbUpgrade[];
  psb_slopes?: PsbSlope[];
  psb_layers?: PsbLayer[];
  isAllSegmentsVerified?: boolean;
  psb_selected_materials: PsbSelectedMaterial[];
  psb_material_calculations: PsbMaterialCalculation[];
  psb_louvrevents: PsbLouveredVent
  psb_soffitvents: PsbSoffitVent

  constructor() {
    this.id = null;
    this.wasting = null;
    this.id_inwshield_rows = null;
    // this.inwshield_rows = null;
    this.id_project_building = null;
    this.ridge_lf = null;
    this.hips_lf = null;
    this.eves_rakes_lf_flat_roof = null;
    this.id_metal_eves_rakes_flat_roof = null;
    this.eves_starters_lf_low_slope = null;
    this.id_metal_eves_starters_low_slope = null;
    this.rakes_lf_low_steep_slope = null;
    this.rakes_lf_steep_slope = null;
    this.id_metal_rakes_low_steep_slope = null;
    this.valleys_lf_low_slope = null;
    this.eves_starters_lf_steep_slope = null;
    this.id_metal_lss_starters_lf = null;
    this.valleys_lf_steep_slope = null;
    this.project_warranty_type_requested = [];
    this.id_project_warranty_option = null;
    this.id_cost_int_windw = null;
    this.verified_general = null;
    this.verified_roof_slope = null;
    this.psb_verifieds = [];
    this.misc_roof_caulking_pc = null;
    this.misc_spary_paint_pc = null;
    this.misc_poor_access_dll = null;
    this.misc_miscellaneous_dll = null;
    this.misc_permit_dll = null;
    this.misc_contingency_fund_dll = null;
    this.vent_j_vent_4_pc = null;
    this.vent_j_vent_6_pc = null;
    this.vent_is_ridgevent_in_place = null;
    this.vent_ridgevent_lf = null;
    this.vent_metal_artict_replace = null;
    this.vent_metal_artict_add = null;
    this.vent_metal_artict_remove = null;
    this.vent_metal_artict_relocate = null;
    this.vent_metal_artict_cut_in_pc = null;
    this.vent_solar_power_vent_pc = null;
    this.vent_power_vent_pc = null;
    this.flash_step_4_4_8_lf = null;
    this.flash_rolled_metal_20_50_lf = null;
    this.flash_end_wall_metal_3_5_10_lf = null;
    this.flash_pipe_3_in_1_pc = null;
    this.flash_pipe_2_in_1_pc = null;
    this.flash_retrofit_pipe_pc = null;
    this.flash_step_4_4_12_lf = null;
    this.vent_soffit_eves_in = null;
    this.vent_soffit_rakes_in = null;
    this.vent_additional_soffit_eves_sf = null;
    this.vent_cut_sidding_walls_lf = null;
    this.out_additional_fuel_dll = null;
    this.out_estimated_days_days = null;
    this.out_estimated_roofers_qty = null;
    this.out_loding_rate_dll = null;
    this.out_id_loding_type = null;
    this.out_travel_time_hrs = null;
    this.isModified = null;
    this.psb_options = [];
    this.psb_slopes = [];
    this.psb_layers = [];
    this.isAllSegmentsVerified = null;
    this.psb_selected_materials = null;
  }
}
