import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class CatalogsService {
  public materialList = [];

  constructor() {}

  getInWShieldRows = () => {
    return [
      {
        inwsield_rows_option: 'Ice and Water Shield declined',
        rows_eves: 0,
        rows_valleys: 0,
        id: 3,
      },
      {
        inwsield_rows_option: 'Complete roof',
        rows_eves: -1,
        rows_valleys: -1,
        id: 4,
      },
      {
        inwsield_rows_option: '3 Feet on eves+ 3 feet on Valleys',
        rows_eves: 1,
        rows_valleys: 1,
        id: 1,
      },
      {
        inwsield_rows_option: '6 Feet on eves+ 3 feet on Valleys',
        rows_eves: 2,
        rows_valleys: 1,
        id: 2,
      },
    ];
  };

  getExpensesList = () => {
    return [
      {
        concept: 'Poor access',
        id: 1,
      },
      {
        concept: 'Miscellaneous',
        id: 2,
      },
      {
        concept: 'Permit',
        id: 3,
      },
      {
        concept: 'Contigency Fund',
        id: 4,
      },
      {
        concept: 'Additional Fuel',
        id: 6,
      },
      {
        concept: 'Loding',
        id: 5,
      },
      {
        concept: 'Perdium',
        id: 7,
      },
    ];
  };

  getLaborPrices = () => {
    return [
      {
        id: 1,
        labor: 'Valley "W" Metal LF\'',
        price: 1,
        unit: 'p/foot',
      },
      {
        id: 2,
        labor: 'Cut In New Vents',
        price: 10,
        unit: 'each',
      },
      {
        id: 3,
        labor: 'Cut Siding',
        price: 1,
        unit: 'p/foot',
      },
      {
        id: 4,
        labor: 'Plug in Existing Vents',
        price: 10,
        unit: 'each',
      },
      {
        id: 5,
        labor: "Ridge Vent (Cut In) LF'",
        price: 1.25,
        unit: 'p/foot',
      },
      {
        id: 6,
        labor: 'Install Power Vents',
        price: 50,
        unit: 'each',
      },
      {
        id: 7,
        labor: 'Chimney Flashing  (Large)',
        price: 100,
        unit: 'each',
      },
      {
        id: 8,
        labor: 'Chimney Flashing  (Small)',
        price: 50,
        unit: 'each',
      },
      {
        id: 9,
        labor: "Step Flashing LF'",
        price: 1,
        unit: 'p/foot',
      },
      {
        id: 10,
        labor: '2X2 Velux Skylight (Curb Mount)',
        price: 50,
        unit: 'each',
      },
      {
        id: 11,
        labor: '2x4 Velux Skylight (Curb Mount)',
        price: 100,
        unit: 'each',
      },
      {
        id: 12,
        labor: 'Poor Access',
        price: 350,
        unit: 'each',
      },
      {
        id: 13,
        labor: 'Side wall install',
        price: 1,
        unit: 'p/foot',
      },
      {
        id: 14,
        labor: 'Reglet',
        price: 1,
        unit: 'p/foot',
      },
      {
        id: 15,
        labor: 'SA CAP',
        price: 65,
        unit: 'sq',
      },
    ];
  };

  getMaterialUnits = () => {
    return [
      {
        id: 1,
        unit: 'Pieces',
        abbreviation: 'PC',
      },
      {
        id: 2,
        unit: 'Squares',
        abbreviation: 'SQ',
      },
      {
        id: 3,
        unit: 'Bundles',
        abbreviation: 'BUNDLES',
      },
      {
        id: 4,
        unit: 'Boxes',
        abbreviation: 'BOXES',
      },
      {
        id: 5,
        unit: 'Linear Feet',
        abbreviation: 'LF',
      },
      {
        id: 6,
        unit: 'Dollars',
        abbreviation: 'DLL',
      },
      {
        id: 7,
        unit: '1/4 Boxes',
        abbreviation: '1/4 BOXES',
      },
      {
        id: 8,
        unit: 'Rolls',
        abbreviation: 'ROLLS',
      },
      {
        id: 9,
        unit: 'Hours',
        abbreviation: 'HR',
      },
    ];
  };

  getPriceList = () => {
    return [
      {
        "id" : 1,
        "start_date" : "2022-04-06",
        "is_current" : true,
        "id_supplier" : 1
      },
      {
        "id" : 2,
        "start_date" : "2022-04-06",
        "is_current" : true,
        "id_supplier" : 2
      },
      {
        "id" : 3,
        "start_date" : "2022-01-01",
        "is_current" : false,
        "id_supplier" : 1
      },
      {
        "id" : 4,
        "start_date" : "2022-02-02",
        "is_current" : false,
        "id_supplier" : 2
      },
      {
        "id" : 5,
        "start_date" : "2022-09-28",
        "is_current" : true,
        "id_supplier" : 3
      },
      {
        "id" : 7,
        "start_date" : "2022-09-28",
        "is_current" : true,
        "id_supplier" : 5
      },
      {
        "id" : 6,
        "start_date" : "2022-09-28",
        "is_current" : true,
        "id_supplier" : 4
      }
    ];
  };

  getSuppliers = () => {
    return  [
      {
        "id" : 1,
        "supplier" : "ABC"
      },
      {
        "id" : 2,
        "supplier" : "Roofing Direct"
      },
      {
        "id" : 3,
        "supplier" : "Home Depot"
      },
      {
        "id" : 4,
        "supplier" : "S&Sales Corporation  "
      },
      {
        "id" : 5,
        "supplier" : "LOWES"
      }
    ];
  };

  getMaterialList = () => {
    return this.materialList;
  };

  selectMaterialList = (priceListDate) => {
    let ids = priceListDate.flatMap((dates) => {
      return dates.id;
    });
    const prices = [
      {
        "id" : 56,
        "material" : "11\"-20' Roll",
        "id_material_type" : 76,
        "coverage_sq" : null,
        "coverage_lf" : 20,
        "id_unit_buy" : 8,
        "unit" : "Rolls",
        "abbreviation" : "ROLLS",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "11\"-20' Roll",
        "bidsheet_order" : 21,
        "id_material_category" : 15,
        "category_bid_sheet_order" : 14,
        "id_price_list" : 1,
        "cost" : 74.80,
        "id_material_price_list" : 55,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 57,
        "material" : "11\"-4' Pieces",
        "id_material_type" : 77,
        "coverage_sq" : null,
        "coverage_lf" : 4,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "11\"-4' Pieces",
        "bidsheet_order" : 21,
        "id_material_category" : 15,
        "category_bid_sheet_order" : 14,
        "id_price_list" : 1,
        "cost" : 32.72,
        "id_material_price_list" : 56,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 1,
        "material" : "1\" D Metal",
        "id_material_type" : 1,
        "coverage_sq" : null,
        "coverage_lf" : 10,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "1\" D metal",
        "bidsheet_order" : 7,
        "id_material_category" : 1,
        "category_bid_sheet_order" : 7,
        "id_price_list" : 2,
        "cost" : 6.35,
        "id_material_price_list" : 11,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 3,
        "material" : "1\" x 5\" D Metal",
        "id_material_type" : 3,
        "coverage_sq" : null,
        "coverage_lf" : 10,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "1\" x 5\" D metal",
        "bidsheet_order" : 9,
        "id_material_category" : 1,
        "category_bid_sheet_order" : 7,
        "id_price_list" : 1,
        "cost" : 12,
        "id_material_price_list" : 13,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 2,
        "material" : "2\" D Metal",
        "id_material_type" : 2,
        "coverage_sq" : null,
        "coverage_lf" : 10,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "2\" D metal",
        "bidsheet_order" : 8,
        "id_material_category" : 1,
        "category_bid_sheet_order" : 7,
        "id_price_list" : 2,
        "cost" : 9.35,
        "id_material_price_list" : 12,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 54,
        "material" : "9\"-20' Roll",
        "id_material_type" : 74,
        "coverage_sq" : null,
        "coverage_lf" : 20,
        "id_unit_buy" : 8,
        "unit" : "Rolls",
        "abbreviation" : "ROLLS",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "9\"-20' Roll",
        "bidsheet_order" : 21,
        "id_material_category" : 15,
        "category_bid_sheet_order" : 14,
        "id_price_list" : 1,
        "cost" : 74.80,
        "id_material_price_list" : 53,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 55,
        "material" : "9\"-4' Pieces",
        "id_material_type" : 75,
        "coverage_sq" : null,
        "coverage_lf" : 4,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "9\"-4' Pieces",
        "bidsheet_order" : 21,
        "id_material_category" : 15,
        "category_bid_sheet_order" : 14,
        "id_price_list" : 1,
        "cost" : 30,
        "id_material_price_list" : 54,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 41,
        "material" : "CERT WINTERGUARD GRAN",
        "id_material_type" : 52,
        "coverage_sq" : 1.98,
        "coverage_lf" : 195,
        "id_unit_buy" : 8,
        "unit" : "Rolls",
        "abbreviation" : "ROLLS",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "CERT WINTERGUARD GRAN",
        "bidsheet_order" : 33,
        "id_material_category" : 30,
        "category_bid_sheet_order" : 29,
        "id_price_list" : 1,
        "cost" : 106.50,
        "id_material_price_list" : 43,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 42,
        "material" : "CER WINTERGUARD HT",
        "id_material_type" : 51,
        "coverage_sq" : 1.98,
        "coverage_lf" : 195,
        "id_unit_buy" : 8,
        "unit" : "Rolls",
        "abbreviation" : "ROLLS",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "CER WINTERGUARD HT",
        "bidsheet_order" : 32,
        "id_material_category" : 30,
        "category_bid_sheet_order" : 29,
        "id_price_list" : 1,
        "cost" : 167.5,
        "id_material_price_list" : 44,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 36,
        "material" : "Clips",
        "id_material_type" : 49,
        "coverage_sq" : 20,
        "coverage_lf" : 1,
        "id_unit_buy" : 6,
        "unit" : "Dollars",
        "abbreviation" : "DLL",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "Clips",
        "bidsheet_order" : 35,
        "id_material_category" : 29,
        "category_bid_sheet_order" : 28,
        "id_price_list" : 2,
        "cost" : 20.24,
        "id_material_price_list" : 42,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 39,
        "material" : "Coil nails 1 1\/4",
        "id_material_type" : 44,
        "coverage_sq" : null,
        "coverage_lf" : 17,
        "id_unit_buy" : 4,
        "unit" : "Boxes",
        "abbreviation" : "BOXES",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "Coil nails 1 1\/4",
        "bidsheet_order" : 30,
        "id_material_category" : 32,
        "category_bid_sheet_order" : 31,
        "id_price_list" : 2,
        "cost" : 50.60,
        "id_material_price_list" : 34,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 38,
        "material" : "Coil nails 7\/8",
        "id_material_type" : 43,
        "coverage_sq" : null,
        "coverage_lf" : 17,
        "id_unit_buy" : 4,
        "unit" : "Boxes",
        "abbreviation" : "BOXES",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "Coil nails 7\/8",
        "bidsheet_order" : 29,
        "id_material_category" : 31,
        "category_bid_sheet_order" : 30,
        "id_price_list" : 1,
        "cost" : 49.29,
        "id_material_price_list" : 33,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 4,
        "material" : "CT Landmark",
        "id_material_type" : 4,
        "coverage_sq" : 0.33,
        "coverage_lf" : null,
        "id_unit_buy" : 2,
        "unit" : "Squares",
        "abbreviation" : "SQ",
        "id_trademark" : 1,
        "trademark" : "CertainTed",
        "id_supplier" : 1,
        "material_type" : "CT Landmark",
        "bidsheet_order" : 1,
        "id_material_category" : 2,
        "category_bid_sheet_order" : 1,
        "id_price_list" : 1,
        "cost" : 107.49,
        "id_material_price_list" : 1,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 7,
        "material" : "CT Presidential",
        "id_material_type" : 18,
        "coverage_sq" : 0.2,
        "coverage_lf" : null,
        "id_unit_buy" : 2,
        "unit" : "Squares",
        "abbreviation" : "SQ",
        "id_trademark" : 1,
        "trademark" : "CertainTed",
        "id_supplier" : 1,
        "material_type" : "CT Presidential",
        "bidsheet_order" : 4,
        "id_material_category" : 3,
        "category_bid_sheet_order" : 2,
        "id_price_list" : 1,
        "cost" : 181.80,
        "id_material_price_list" : 4,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 9,
        "material" : "CT SWIFT STARTER",
        "id_material_type" : 19,
        "coverage_sq" : 100,
        "coverage_lf" : null,
        "id_unit_buy" : 3,
        "unit" : "Bundles",
        "abbreviation" : "BUNDLES",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "CT SWIFT STARTER",
        "bidsheet_order" : 10,
        "id_material_category" : 4,
        "category_bid_sheet_order" : 3,
        "id_price_list" : 1,
        "cost" : 63.60,
        "id_material_price_list" : 6,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 24,
        "material" : "3\" x 5\"",
        "id_material_type" : 38,
        "coverage_sq" : null,
        "coverage_lf" : 10,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "END WALL METAL (3X5X10)",
        "bidsheet_order" : 24,
        "id_material_category" : 22,
        "category_bid_sheet_order" : 17,
        "id_price_list" : 2,
        "cost" : 10.84,
        "id_material_price_list" : 24,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 48,
        "material" : "Epilay Protectite Plasfelt #15",
        "id_material_type" : 58,
        "coverage_sq" : 9.5,
        "coverage_lf" : null,
        "id_unit_buy" : 8,
        "unit" : "Rolls",
        "abbreviation" : "ROLLS",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "Epilay Protectite Plasfelt #15",
        "bidsheet_order" : 31,
        "id_material_category" : 34,
        "category_bid_sheet_order" : 33,
        "id_price_list" : 2,
        "cost" : 51.70,
        "id_material_price_list" : 49,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 14,
        "material" : "J Vent 4\"",
        "id_material_type" : 25,
        "coverage_sq" : null,
        "coverage_lf" : null,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "J Vent 4\"",
        "bidsheet_order" : 15,
        "id_material_category" : 9,
        "category_bid_sheet_order" : 8,
        "id_price_list" : 2,
        "cost" : 11.83,
        "id_material_price_list" : 14,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 15,
        "material" : "J Vent 6\"",
        "id_material_type" : 26,
        "coverage_sq" : null,
        "coverage_lf" : null,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "J Vent  6\"",
        "bidsheet_order" : 16,
        "id_material_category" : 10,
        "category_bid_sheet_order" : 9,
        "id_price_list" : 2,
        "cost" : 16.37,
        "id_material_price_list" : 15,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 43,
        "material" : "Malarkey Arctic Seal 401",
        "id_material_type" : 50,
        "coverage_sq" : 1.98,
        "coverage_lf" : 65,
        "id_unit_buy" : 8,
        "unit" : "Rolls",
        "abbreviation" : "ROLLS",
        "id_trademark" : 3,
        "trademark" : "Malarkeys",
        "id_supplier" : 2,
        "material_type" : "Malarkey Arctic Seal 401",
        "bidsheet_order" : 31,
        "id_material_category" : 30,
        "category_bid_sheet_order" : 29,
        "id_price_list" : 2,
        "cost" : 63.8,
        "id_material_price_list" : 45,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 62,
        "material" : "Malarkey highlander",
        "id_material_type" : 13,
        "coverage_sq" : 0.33,
        "coverage_lf" : null,
        "id_unit_buy" : 2,
        "unit" : "Squares",
        "abbreviation" : "SQ",
        "id_trademark" : 3,
        "trademark" : "Malarkeys",
        "id_supplier" : 2,
        "material_type" : "Malarkey highlander",
        "bidsheet_order" : 1,
        "id_material_category" : 2,
        "category_bid_sheet_order" : 1,
        "id_price_list" : 2,
        "cost" : 106.98,
        "id_material_price_list" : 59,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 64,
        "material" : "Malarkey legacy",
        "id_material_type" : 15,
        "coverage_sq" : 0.25,
        "coverage_lf" : null,
        "id_unit_buy" : 2,
        "unit" : "Squares",
        "abbreviation" : "SQ",
        "id_trademark" : 3,
        "trademark" : "Malarkeys",
        "id_supplier" : 2,
        "material_type" : "Malarkey legacy",
        "bidsheet_order" : 3,
        "id_material_category" : 36,
        "category_bid_sheet_order" : 1,
        "id_price_list" : 2,
        "cost" : 161.76,
        "id_material_price_list" : 61,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 50,
        "material" : "Malarkey Secure start Plus #30",
        "id_material_type" : 60,
        "coverage_sq" : 9.5,
        "coverage_lf" : null,
        "id_unit_buy" : 8,
        "unit" : "Rolls",
        "abbreviation" : "ROLLS",
        "id_trademark" : 3,
        "trademark" : "Malarkeys",
        "id_supplier" : 1,
        "material_type" : "Malarkey Secure start Plus #30",
        "bidsheet_order" : 33,
        "id_material_category" : 34,
        "category_bid_sheet_order" : 33,
        "id_price_list" : 1,
        "cost" : 164.25,
        "id_material_price_list" : 51,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 49,
        "material" : "Malarkey Secure start SG #15",
        "id_material_type" : 59,
        "coverage_sq" : 9.5,
        "coverage_lf" : null,
        "id_unit_buy" : 8,
        "unit" : "Rolls",
        "abbreviation" : "ROLLS",
        "id_trademark" : 3,
        "trademark" : "Malarkeys",
        "id_supplier" : 1,
        "material_type" : "Malarkey Secure start SG #15",
        "bidsheet_order" : 32,
        "id_material_category" : 34,
        "category_bid_sheet_order" : 33,
        "id_price_list" : 1,
        "cost" : 132,
        "id_material_price_list" : 50,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 63,
        "material" : "Malarkey Vista",
        "id_material_type" : 14,
        "coverage_sq" : 0.33,
        "coverage_lf" : null,
        "id_unit_buy" : 2,
        "unit" : "Squares",
        "abbreviation" : "SQ",
        "id_trademark" : 3,
        "trademark" : "Malarkeys",
        "id_supplier" : 2,
        "material_type" : "Malarkey Vista",
        "bidsheet_order" : 2,
        "id_material_category" : 2,
        "category_bid_sheet_order" : 1,
        "id_price_list" : 2,
        "cost" : 110.97,
        "id_material_price_list" : 60,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 65,
        "material" : "Malarkey Windsor",
        "id_material_type" : 16,
        "coverage_sq" : 0.20,
        "coverage_lf" : null,
        "id_unit_buy" : 2,
        "unit" : "Squares",
        "abbreviation" : "SQ",
        "id_trademark" : 3,
        "trademark" : "Malarkeys",
        "id_supplier" : 2,
        "material_type" : "Malarkey Windsor",
        "bidsheet_order" : 4,
        "id_material_category" : 3,
        "category_bid_sheet_order" : 2,
        "id_price_list" : 2,
        "cost" : 197.10,
        "id_material_price_list" : 62,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 12,
        "material" : "MOUNTAIN RIDGE 10\" (20lf)",
        "id_material_type" : 22,
        "coverage_sq" : 20,
        "coverage_lf" : null,
        "id_unit_buy" : 4,
        "unit" : "Boxes",
        "abbreviation" : "BOXES",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "MOUNTAIN RIDGE 10\" (20lf)",
        "bidsheet_order" : 13,
        "id_material_category" : 7,
        "category_bid_sheet_order" : 5,
        "id_price_list" : 1,
        "cost" : 84.46,
        "id_material_price_list" : 9,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 59,
        "material" : "O.C. Duration",
        "id_material_type" : 10,
        "coverage_sq" : 0.33,
        "coverage_lf" : null,
        "id_unit_buy" : 2,
        "unit" : "Squares",
        "abbreviation" : "SQ",
        "id_trademark" : 2,
        "trademark" : "Owens Corning",
        "id_supplier" : 1,
        "material_type" : "O.C. Duration",
        "bidsheet_order" : 2,
        "id_material_category" : 36,
        "category_bid_sheet_order" : 1,
        "id_price_list" : 1,
        "cost" : 114,
        "id_material_price_list" : 58,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 58,
        "material" : "O.C. Oakridge",
        "id_material_type" : 9,
        "coverage_sq" : 0.33,
        "coverage_lf" : null,
        "id_unit_buy" : 2,
        "unit" : "Squares",
        "abbreviation" : "SQ",
        "id_trademark" : 2,
        "trademark" : "Owens Corning",
        "id_supplier" : 1,
        "material_type" : "O.C. Oakridge",
        "bidsheet_order" : 1,
        "id_material_category" : 2,
        "category_bid_sheet_order" : 1,
        "id_price_list" : 1,
        "cost" : 105,
        "id_material_price_list" : 57,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 45,
        "material" : "OC WEATHERLOCK FLEX 2.25 SQ",
        "id_material_type" : 54,
        "coverage_sq" : 2.25,
        "coverage_lf" : 65,
        "id_unit_buy" : 8,
        "unit" : "Rolls",
        "abbreviation" : "ROLLS",
        "id_trademark" : 2,
        "trademark" : "Owens Corning",
        "id_supplier" : 1,
        "material_type" : "OC WEATHERLOCK FLEX 2.25 SQ",
        "bidsheet_order" : 35,
        "id_material_category" : 30,
        "category_bid_sheet_order" : 29,
        "id_price_list" : 1,
        "cost" : 167,
        "id_material_price_list" : 47,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 44,
        "material" : "OC WEATHERLOCK MAT 2 SQ",
        "id_material_type" : 53,
        "coverage_sq" : 1.98,
        "coverage_lf" : 65,
        "id_unit_buy" : 8,
        "unit" : "Rolls",
        "abbreviation" : "ROLLS",
        "id_trademark" : 2,
        "trademark" : "Owens Corning",
        "id_supplier" : 1,
        "material_type" : "OC WEATHERLOCK MAT 2 SQ",
        "bidsheet_order" : 34,
        "id_material_category" : 30,
        "category_bid_sheet_order" : 29,
        "id_price_list" : 1,
        "cost" : 99,
        "id_material_price_list" : 46,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 34,
        "material" : "OBS",
        "id_material_type" : 47,
        "coverage_sq" : 0.32,
        "coverage_lf" : 1,
        "id_unit_buy" : 6,
        "unit" : "Dollars",
        "abbreviation" : "DLL",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 5,
        "material_type" : "OSB",
        "bidsheet_order" : 33,
        "id_material_category" : 27,
        "category_bid_sheet_order" : 26,
        "id_price_list" : 7,
        "cost" : 15.30,
        "id_material_price_list" : 40,
        "start_date" : "2022-09-28"
      },
      {
        "id" : 28,
        "material" : "Pipe Flashing  (Jacks) 3\" ,4\"",
        "id_material_type" : 36,
        "coverage_sq" : null,
        "coverage_lf" : null,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "PIPE FLASHING 2IN1",
        "bidsheet_order" : 27,
        "id_material_category" : 20,
        "category_bid_sheet_order" : 20,
        "id_price_list" : 2,
        "cost" : 10.49,
        "id_material_price_list" : 28,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 27,
        "material" : "Pipe Flashings (Jacks) 1\",2\",3\"",
        "id_material_type" : 35,
        "coverage_sq" : null,
        "coverage_lf" : null,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "PIPE FLASHING 3IN1",
        "bidsheet_order" : 26,
        "id_material_category" : 19,
        "category_bid_sheet_order" : 19,
        "id_price_list" : 2,
        "cost" : 9.63,
        "id_material_price_list" : 27,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 40,
        "material" : "Plastic caps",
        "id_material_type" : 42,
        "coverage_sq" : 30,
        "coverage_lf" : 10,
        "id_unit_buy" : 3,
        "unit" : "Bundles",
        "abbreviation" : "BUNDLES",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "Plastic caps",
        "bidsheet_order" : 28,
        "id_material_category" : 33,
        "category_bid_sheet_order" : 32,
        "id_price_list" : 2,
        "cost" : 21.86,
        "id_material_price_list" : 35,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 18,
        "material" : "Power vent",
        "id_material_type" : 29,
        "coverage_sq" : null,
        "coverage_lf" : null,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "Power vent",
        "bidsheet_order" : 19,
        "id_material_category" : 13,
        "category_bid_sheet_order" : 12,
        "id_price_list" : 1,
        "cost" : 302,
        "id_material_price_list" : 18,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 10,
        "material" : "PRESIDENTIAL STARTER",
        "id_material_type" : 20,
        "coverage_sq" : 70,
        "coverage_lf" : null,
        "id_unit_buy" : 3,
        "unit" : "Bundles",
        "abbreviation" : "BUNDLES",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "PRESIDENTIAL STARTER",
        "bidsheet_order" : 11,
        "id_material_category" : 6,
        "category_bid_sheet_order" : 4,
        "id_price_list" : 1,
        "cost" : 89.24,
        "id_material_price_list" : 7,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 13,
        "material" : "RAPID RIDGE 10\" (20lf)",
        "id_material_type" : 23,
        "coverage_sq" : 20,
        "coverage_lf" : null,
        "id_unit_buy" : 4,
        "unit" : "Boxes",
        "abbreviation" : "BOXES",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "RAPID RIDGE 10\" (20lf)",
        "bidsheet_order" : 14,
        "id_material_category" : 7,
        "category_bid_sheet_order" : 5,
        "id_price_list" : 1,
        "cost" : 71.76,
        "id_material_price_list" : 10,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 30,
        "material" : "Residential ZIP-SEAL Retro Flashing",
        "id_material_type" : 37,
        "coverage_sq" : null,
        "coverage_lf" : null,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "RETROFIT PIPE FLASHING",
        "bidsheet_order" : 28,
        "id_material_category" : 21,
        "category_bid_sheet_order" : 21,
        "id_price_list" : 2,
        "cost" : 24.05,
        "id_material_price_list" : 36,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 53,
        "material" : "RHINO 15 SYN UL #15",
        "id_material_type" : 61,
        "coverage_sq" : 9.5,
        "coverage_lf" : null,
        "id_unit_buy" : 8,
        "unit" : "Rolls",
        "abbreviation" : "ROLLS",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "RHINO 15 SYN UL #15",
        "bidsheet_order" : 34,
        "id_material_category" : 34,
        "category_bid_sheet_order" : 33,
        "id_price_list" : 1,
        "cost" : 81.86,
        "id_material_price_list" : 52,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 26,
        "material" : "Rolled Metal 20\"x50'",
        "id_material_type" : 34,
        "coverage_sq" : null,
        "coverage_lf" : 1,
        "id_unit_buy" : 5,
        "unit" : "Linear Feet",
        "abbreviation" : "LF",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "ROLLED METAL",
        "bidsheet_order" : 25,
        "id_material_category" : 18,
        "category_bid_sheet_order" : 18,
        "id_price_list" : 2,
        "cost" : 132,
        "id_material_price_list" : 26,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 33,
        "material" : "ROOF CAULKING",
        "id_material_type" : 45,
        "coverage_sq" : null,
        "coverage_lf" : null,
        "id_unit_buy" : 6,
        "unit" : "Dollars",
        "abbreviation" : "DLL",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 4,
        "material_type" : "ROOF CAULKING",
        "bidsheet_order" : 31,
        "id_material_category" : 24,
        "category_bid_sheet_order" : 23,
        "id_price_list" : 6,
        "cost" : 7,
        "id_material_price_list" : 37,
        "start_date" : "2022-09-28"
      },
      {
        "id" : 16,
        "material" : "Roof Vent 038",
        "id_material_type" : 27,
        "coverage_sq" : null,
        "coverage_lf" : null,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "Roof Vent 038",
        "bidsheet_order" : 17,
        "id_material_category" : 11,
        "category_bid_sheet_order" : 10,
        "id_price_list" : 1,
        "cost" : 18,
        "id_material_price_list" : 16,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 37,
        "material" : "Malarkey Omni CAP SA",
        "id_material_type" : 46,
        "coverage_sq" : 1,
        "coverage_lf" : null,
        "id_unit_buy" : 6,
        "unit" : "Dollars",
        "abbreviation" : "DLL",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "SA Cap",
        "bidsheet_order" : 32,
        "id_material_category" : 26,
        "category_bid_sheet_order" : 25,
        "id_price_list" : 1,
        "cost" : 115.31,
        "id_material_price_list" : 39,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 67,
        "material" : "Owens Corning deckseal CAP Sheet",
        "id_material_type" : 46,
        "coverage_sq" : 1,
        "coverage_lf" : null,
        "id_unit_buy" : 6,
        "unit" : "Dollars",
        "abbreviation" : "DLL",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "SA Cap",
        "bidsheet_order" : 32,
        "id_material_category" : 26,
        "category_bid_sheet_order" : 25,
        "id_price_list" : 1,
        "cost" : 130.29,
        "id_material_price_list" : 63,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 11,
        "material" : "SHADOW RIDGE 12\" (30lf)",
        "id_material_type" : 21,
        "coverage_sq" : 30,
        "coverage_lf" : null,
        "id_unit_buy" : 3,
        "unit" : "Bundles",
        "abbreviation" : "BUNDLES",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "SHADOW RIDGE 12\" (30lf)",
        "bidsheet_order" : 12,
        "id_material_category" : 7,
        "category_bid_sheet_order" : 5,
        "id_price_list" : 1,
        "cost" : 69.69,
        "id_material_price_list" : 8,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 20,
        "material" : "CT SHINGLEVENT 11\"",
        "id_material_type" : 31,
        "coverage_sq" : null,
        "coverage_lf" : 4,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : 1,
        "trademark" : "CertainTed",
        "id_supplier" : 1,
        "material_type" : "SHINGLEVENT 11\"",
        "bidsheet_order" : 21,
        "id_material_category" : 15,
        "category_bid_sheet_order" : 14,
        "id_price_list" : 1,
        "cost" : 15,
        "id_material_price_list" : 20,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 19,
        "material" : "CT SHINGLEVENT 9\"",
        "id_material_type" : 30,
        "coverage_sq" : null,
        "coverage_lf" : 4,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : 1,
        "trademark" : "CertainTed",
        "id_supplier" : 1,
        "material_type" : "SHINGLEVENT 9\"",
        "bidsheet_order" : 20,
        "id_material_category" : 15,
        "category_bid_sheet_order" : 14,
        "id_price_list" : 1,
        "cost" : 15,
        "id_material_price_list" : 19,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 17,
        "material" : "Solar power vent",
        "id_material_type" : 28,
        "coverage_sq" : null,
        "coverage_lf" : null,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "Solar power vent",
        "bidsheet_order" : 18,
        "id_material_category" : 12,
        "category_bid_sheet_order" : 11,
        "id_price_list" : 1,
        "cost" : 376.29,
        "id_material_price_list" : 17,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 32,
        "material" : "Spray paint",
        "id_material_type" : 41,
        "coverage_sq" : null,
        "coverage_lf" : null,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 3,
        "material_type" : "SPRAY PAINT",
        "bidsheet_order" : 27,
        "id_material_category" : 25,
        "category_bid_sheet_order" : 24,
        "id_price_list" : 5,
        "cost" : 7,
        "id_material_price_list" : 38,
        "start_date" : "2022-09-28"
      },
      {
        "id" : 35,
        "material" : "Staples",
        "id_material_type" : 48,
        "coverage_sq" : 8.75,
        "coverage_lf" : 7,
        "id_unit_buy" : 6,
        "unit" : "Dollars",
        "abbreviation" : "DLL",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "Staples",
        "bidsheet_order" : 34,
        "id_material_category" : 28,
        "category_bid_sheet_order" : 27,
        "id_price_list" : 2,
        "cost" : 50.72,
        "id_material_price_list" : 41,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 25,
        "material" : "Step Flashing 4x4x12",
        "id_material_type" : 33,
        "coverage_sq" : null,
        "coverage_lf" : 24,
        "id_unit_buy" : 3,
        "unit" : "Bundles",
        "abbreviation" : "BUNDLES",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "STEP FLASHING 4X4X12",
        "bidsheet_order" : 23,
        "id_material_category" : 17,
        "category_bid_sheet_order" : 16,
        "id_price_list" : 1,
        "cost" : 62.25,
        "id_material_price_list" : 25,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 23,
        "material" : "Step Flashing 4x4x8",
        "id_material_type" : 32,
        "coverage_sq" : null,
        "coverage_lf" : 37.5,
        "id_unit_buy" : 3,
        "unit" : "Bundles",
        "abbreviation" : "BUNDLES",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 2,
        "material_type" : "STEP FLASHING 4X4X8",
        "bidsheet_order" : 22,
        "id_material_category" : 16,
        "category_bid_sheet_order" : 15,
        "id_price_list" : 2,
        "cost" : 47.85,
        "id_material_price_list" : 23,
        "start_date" : "2022-04-06"
      },
      {
        "id" : 29,
        "material" : "W Metal",
        "id_material_type" : 39,
        "coverage_sq" : null,
        "coverage_lf" : 8.5,
        "id_unit_buy" : 1,
        "unit" : "Pieces",
        "abbreviation" : "PC",
        "id_trademark" : null,
        "trademark" : null,
        "id_supplier" : 1,
        "material_type" : "W Metal",
        "bidsheet_order" : 25,
        "id_material_category" : 23,
        "category_bid_sheet_order" : 22,
        "id_price_list" : 1,
        "cost" : 32.75,
        "id_material_price_list" : 29,
        "start_date" : "2022-04-06"
      }
    ];
    this.materialList = prices.filter((material) => {
      return ids.includes(material.id_price_list);
    });
  };



  getInspectorCostTypes = () => [
    {
      "id" : 1,
      "id_cost_type" : 1,
      "commision_porcentage" : 6,
      "overhead_porcentage" : 25,
      "profit_porcentage" : 6,
      "id_inspector_type" : 1
    },
    {
      "id" : 2,
      "id_cost_type" : 2,
      "commision_porcentage" : 5,
      "overhead_porcentage" : 25,
      "profit_porcentage" : 5,
      "id_inspector_type" : 1
    },
    {
      "id" : 3,
      "id_cost_type" : 3,
      "commision_porcentage" : 4,
      "overhead_porcentage" : 25,
      "profit_porcentage" : 4,
      "id_inspector_type" : 1
    },
    {
      "id" : 4,
      "id_cost_type" : 1,
      "commision_porcentage" : 10,
      "overhead_porcentage" : 25,
      "profit_porcentage" : 5,
      "id_inspector_type" : 2
    },
    {
      "id" : 5,
      "id_cost_type" : 2,
      "commision_porcentage" : 9,
      "overhead_porcentage" : 25,
      "profit_porcentage" : 4,
      "id_inspector_type" : 2
    },
    {
      "id" : 6,
      "id_cost_type" : 3,
      "commision_porcentage" : 8,
      "overhead_porcentage" : 15,
      "profit_porcentage" : 3,
      "id_inspector_type" : 2
    }
  ];

  getInspectorCostTypesFiltered = (idInspectorType: number) => {
    let costs = this.getInspectorCostTypes();
    return costs.filter(cost => cost.id_inspector_type == idInspectorType);
  }
}